---
- name: Docker Network
  community.docker.docker_network:
    name: "{{ node_container_network_name }}"

- name: Celestia node directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    owner: "{{ node_user_id }}"
    group: "{{ node_group_id }}"
    state: directory
  with_items:
    - "{{ node_store_path }}"
    - "{{ node_store_path }}/data"

- name: Celestia copy keys
  ansible.builtin.copy:
    src: "{{ node_keys_source_dir }}"
    dest: "{{ node_store_path }}"
    mode: "0600"
    owner: "{{ node_user_id }}"
    group: "{{ node_group_id }}"
  when: node_keys_source_dir != ""

# The task below will set the container port mapping list by adding a mapping for the gateway port
# if the gateway has been enabled by setting node_gateway to true
- name: Set container port mapping
  ansible.builtin.set_fact:
    container_port_mapping:
      "{{
          [
          node_rpc_ext_port + ':' + node_rpc_int_port,
          node_gateway_ext_port + ':' + node_gateway_int_port if node_gateway else ''
          ]
          | reject('eq', '') | list
      }}"
