---
name: Publish role to ansible-galaxy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v1
        with:
          api_key: ${{ secrets.galaxy_api_key }}